---
title: "Cluster set5"
author: 'User ID: `r Sys.getenv("USER")`'
date: "`r Sys.Date()`"
output:
  html_document:
    fig_height: 7
    fig_width: 9
    keep_md: yes
    toc: yes
    df_print: paged
params:
  out_path: "."
  data_path: "" #path to the seurat object
  sample_name: "merged"
  prefix: "merged"
  num_neighbors_umap: 10
  pcs_name: NULL
  num_dim: 20
  num_neighbors: 20
  resolutions: NULL
  log_file: NULL
  group: "res.0.9" 
---

```{r setup, include=FALSE}
attach(params) 
library(devtools)
load_all("/home/ay1392/anna_beegfs/TET2/scRNAseq/scooter") 
theme_set(theme_bw())
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      fig.path = file.path(out_path, paste0("Cluster-", sample_name, "/")))
```


```{r process_params}
out_path = file.path(out_path, paste0("Cluster-", sample_name))
dir.create(out_path, showWarnings = FALSE)

if(is.null(resolutions)) {
  res = res_range <- c(seq(0.1, 2.5, 0.1), 3, 4, 5, 6, 7, 8, 9)
} else {
  res = resolutions
}
```

# Read in data from somewhere a s_obj 
```{r}
seurat_obj <- readRDS(paste0(data_path, "/seurat_obj.rds"))
```

## Calculate Clusters
```{r}
reduction_names <- c(paste0("umap", num_neighbors_umap, prefix), paste0("pca", prefix))

metadata <- as_data_frame_seurat(seurat_obj = seurat_obj,  
                     reduction = reduction_names, metadata = TRUE)

pcs <- metadata[,str_detect(colnames(metadata), "^PC")]
pcs <- as.data.frame(pcs)
rownames(pcs) <- metadata$cell
clusters <- calculate_clusters(pcs = pcs, num_dim =  num_dim, 
                               log_file = log_file, 
                               num_neighbors = num_neighbors, res = res)

```

```{r}
# put clusters into seurat metadata
seurat_obj@meta.data <- merge_metadata(seurat_obj, clusters)
saveRDS(seurat_obj, file = paste0(out_path, "/", "seurat_obj.rds"))
```

```{r plots}
metadata <- merge_metadata(metadata, clusters)

reduction_names <- paste0("UMAP", num_neighbors_umap, prefix)

plot_dr <- data.frame(X = paste0(reduction_names, "_1"),
                      Y = paste0(reduction_names, "_2"),
                      stringsAsFactors = FALSE)

cluster_path <- file.path(out_path, paste0("cluster-dim.", num_dim, "-neighbors.", num_neighbors))
dir.create(cluster_path, showWarnings = FALSE)

write_excel_csv(metadata, path = paste0(cluster_path, "/", "metadata.csv"))

for(i in 1:nrow(plot_dr)){
  for(j in res) {
  current_plot <- plot_scatter(metadata = metadata,
                               out_path = cluster_path,
                               proj_name = sample_name,
                               log_file = log_file,
                               X = plot_dr[i,1],
                               Y = plot_dr[i,2],
                               color = paste0("res.", j),
                               write = TRUE)
  }
}
```


