---
title: "UMAP-Feature-plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is an R Markdown file. Only text enclosed in the ``` is R code. 

We will load in two libraries: tidyverse, and ggplot2. 

tidyverse is a library that helps us manipulate the data easier.
ggplot2 makes plotting easier. 

By running the command library(ggplot2), we can now use the functions and shortcuts 
that the creators of ggplot2 have packaged into ggplot2. This way, we don't have to 
re-write diffcult code and functions, because there is a contained entity of code (the package) that 
has these functions saved for us to use. 

```{r}
library(tidyverse)
library(ggplot2)
```

There is a function called read_csv in the tidyverse package. It helps us read in csv files.

output <- read_csv(input)

There is one input that you must have for read_csv, the csv file you want to read in. There are
other inputs, which you can look into by typing ?read_csv into the console (most likely in the bottom left quadrant of RStudio) and pressing enter. Or by typing it in these R chunks like I will do below. To run code in an R chunk, highlight the whole section of code you want to run, and then press command and enter, or press the green arrow to the right. 

```{r}
?read_csv
```

We will read in a csv now. 
```{r}
# data will hold the csv after we use the read_csv function
data <- read_csv("/")
```

To inspect the size of data, we can use the function dim()
```{r}
dim(data)
```

We see that it is quite large. Let us look at the column names of data. Since there are so many, we will also use the function head() to only inspect the first 10 colnames.
```{r}
head(colnames(data))
```

Let us look at the rownames of data. 
```{r}
head(rownames(data))
```

Now we will plot a UMAP, using ggplot2.

To plot a UMAP, we need two, maybe three things. The first two are the X axis and Y axis coordinates. These values are in data, there will be two columns that start with UMAPxxxx_1 and UMAPxxxx_2. UMAPxxxx_1 is out X axis and UMAPxxxx_2 is our Y axis. 

Let us find our UMAP coordinates by looking at the first 50 column names. 
```{r}
head(colnames(data), 50)
```

Now that we know 
```{r}

```

